const idList = [
        { shop: '2L鹿児島店', mail : '2l-kagoshima@example.com' },
        { shop: 'DJH宮崎店', mail : 'djh-miyazaki@example.com' },
        { shop: 'DJH都城店', mail : 'djh-miyakonojo@example.com' },
        { shop: 'DJH霧島店', mail : 'djh-kirishima@example.com' },
        { shop: 'DJH鹿児島北店', mail : 'djh-kagoshima-kita@example.com' },
        { shop: 'DJH薩摩川内店', mail : 'djh-sendai@example.com' },
        { shop: 'FH霧島店', mail : 'fh-kirishima@example.com' },
        { shop: 'FH鹿児島店', mail : 'fh-kagoshima@example.com' },
        { shop: 'KH出水阿久根店', mail : 'kh-izumi-akune@example.com' },
        { shop: 'KH大分店', mail : 'kh-ooita@example.com' },
        { shop: 'KH姶良店', mail : 'kh-aira@example.com' },
        { shop: 'KH宮崎店', mail : 'kh-miyazaki@example.com' },
        { shop: 'KH延岡店', mail : 'kh-nobeoka@example.com' },
        { shop: 'KH薩摩川内店', mail : 'kh-sendai@example.com' },
        { shop: 'KH都城店', mail : 'kh-miyakonojo@example.com' },
        { shop: 'KH霧島店', mail : 'kh-kirishima@example.com' },
        { shop: 'KH鹿児島店', mail : 'kh-kagoshima@example.com' },
        { shop: 'KH鹿屋店', mail : 'kh-kanoya@example.com' },
        { shop: 'なごみ姶良霧島店', mail : 'ngm-aira-kirishima@example.com' },
        { shop: 'なごみ鹿児島店', mail : 'ngm-kagoshima@example.com' },
        { shop: 'KH加世田店', mail : 'kh-kaseda@example.com' },
        { shop: 'KH八代店', mail : 'kh-yatsushiro@example.com' },
        { shop: 'KH佐賀店', mail : 'kh-saga@example.com' },
        { shop: 'DJH鹿屋店', mail : 'djh-kanoya@example.com' },
        { shop: 'PG HOUSE宮崎店', mail : 'pgh-miyazaki@example.com' },
        { shop: 'JH熊本店', mail : 'jh-kumamoto@example.com' },
        { shop: 'JH八代店', mail : 'jh-yatsushiro@example.com' },
        { shop: 'KH熊本店', mail : 'kh-kumamoto@example.com' }    
    ];

module.exports = idList;